#include "wled.h"

// AI: below section was generated by an AI
// Registration follows usermods/user_fx/user_fx.cpp; audio layout follows
// usermods/audioreactive/audio_reactive.cpp (WLED upstream 92064ae3).
namespace {

// Map WLED's 5-bit slider to a 0-255 audio threshold. Keep 0-8 unchanged
// for quiet inputs, then widen the steps progressively for amplified input.
uint8_t noiseFloorFromSlider(uint8_t slider) {
  const uint32_t upper = slider > 8 ? slider - 8 : 0;
  return slider + upper * upper * 224U / 529U;
}

// A logarithmic gain gives similar relative adjustment across quiet and loud inputs.
// Slider 0 disables response, 171 is unity, and each 21 steps doubles the gain.
float sensitivityFromSlider(uint8_t slider) {
  return slider == 0 ? 0.0f : exp2f((int(slider) - 171) / 21.0f);
}

// Render a uniform RGBW color with immediate attack and a timed linear release.
// The envelope belongs to the segment, so multiple segments react independently.
void modeVolumeDimmer() {
  const uint8_t minimum = SEGMENT.custom1;
  const uint8_t maximum = max(minimum, SEGMENT.custom2);
  const uint8_t noiseFloor = noiseFloorFromSlider(SEGMENT.custom3);
  uint16_t target = 0;

  um_data_t* audio = nullptr;
  if (UsermodManager::getUMData(&audio, USERMOD_ID_AUDIOREACTIVE) &&
      audio && audio->u_size > 1 && audio->u_data && audio->u_data[1]) {
    // AudioReactive's raw volume already includes its squelch and gain/AGC.
    // Use it rather than the limited/smoothed volume to retain sharp attacks.
    const int16_t volume = *static_cast<int16_t*>(audio->u_data[1]);
    if (volume > noiseFloor) {
      // Preserve sub-unit levels in the Q8 envelope instead of rounding before scaling.
      const float amplified = (volume - noiseFloor) * sensitivityFromSlider(SEGMENT.intensity);
      target = uint16_t(min(amplified, 255.0f) * 256.0f);
    }
  }

  const uint32_t now = millis();
  if (SEGENV.call == 0) {
    SEGENV.aux0 = 0;
    SEGENV.step = now;
  }
  const uint32_t elapsed = now - SEGENV.step; // Unsigned subtraction handles timer rollover.
  SEGENV.step = now;

  // Q8 precision avoids rounding a small decay to zero at high frame rates.
  // Decay selects the time to fall from full response to the floor: 50-2090 ms.
  const uint32_t releaseMs = 50U + uint32_t(SEGMENT.speed) * 8U;
  const uint32_t fall = min(elapsed, releaseMs) * (255U << 8) / releaseMs;
  const uint16_t decayed = fall >= SEGENV.aux0 ? 0 : SEGENV.aux0 - fall;
  SEGENV.aux0 = max(target, decayed);

  const uint8_t level = minimum + uint32_t(maximum - minimum) * SEGENV.aux0 / (255U << 8);
  SEGMENT.fill(color_blend(BLACK, SEGCOLOR(0), level));
}

static const char effectData[] PROGMEM =
  "Volume Dimmer@Decay,Sensitivity,Minimum brightness,Maximum brightness,Noise floor;!;;012v;sx=32,ix=171,c1=26,c2=255,c3=2";

class PulseEffectUsermod : public Usermod {
public:
  void setup() override {
    strip.addEffect(255, &modeVolumeDimmer, effectData);
  }
  void loop() override {}
};

static PulseEffectUsermod pulseEffect;
} // namespace

REGISTER_USERMOD(pulseEffect);
// AI: end
